# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    # macos-latest
    runs-on: macos-14
    steps:
      - name: Install Xcode.
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # 15.0 / 16-beta etc
          xcode-version: 16-beta
    #   - name: Install just.
    #     uses: extractions/setup-just@v2
      - name: Checkout source.
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build.
        run: swift build -v
    #   - name: Run tests.
    #     run: swift test -v
    #   - name: Build examples.
    #     run: just build-examples
